import { v4 as uuidv4 } from 'uuid';


export const cpuProcessorData = [
    { processor: 'A4', brand: 'AMD ' },
    { processor: 'A6', brand: 'AMD ' },
    { processor: 'A8', brand: 'AMD ' },
    { processor: 'A10', brand: 'AMD ' },
    { processor: 'A12', brand: 'AMD ' },
    { processor: 'Athlon', brand: 'AMD ' },
    { processor: 'Athlon II', brand: 'AMD ' },
    { processor: 'Athlon II X2', brand: 'AMD ' },
    { processor: 'Athlon II X3', brand: 'AMD ' },
    { processor: 'Athlon II X4', brand: 'AMD ' },
    { processor: 'Athlon X2', brand: 'AMD ' },
    { processor: 'Athlon X4', brand: 'AMD ' },
    { processor: 'E2-Series', brand: 'AMD ' },
    { processor: 'FX', brand: 'AMD ' },
    { processor: 'Opteron', brand: 'AMD ' },
    { processor: 'Phenom II X2', brand: 'AMD ' },
    { processor: 'Phenom II X3', brand: 'AMD ' },
    { processor: 'Phenom II X4', brand: 'AMD ' },
    { processor: 'Phenom II X6', brand: 'AMD ' },
    { processor: 'Ryzen 3', brand: 'AMD ' },
    { processor: 'Ryzen 5', brand: 'AMD ' },
    { processor: 'Ryzen 7', brand: 'AMD ' },
    { processor: 'Ryzen 9', brand: 'AMD ' },
    { processor: 'Sempron', brand: 'AMD ' },
    { processor: 'Sempron X2', brand: 'AMD ' },
    { processor: 'Threadripper', brand: 'AMD ' },
    { processor: 'Celeron', brand: 'Intel' },
    { processor: 'Core 2 Duo', brand: 'Intel' },
    { processor: 'Core 2 Extreme', brand: 'Intel' },
    { processor: 'Core 2 Quad', brand: 'Intel' },
    { processor: 'Core i3', brand: 'Intel' },
    { processor: 'Core i5', brand: 'Intel' },
    { processor: 'Core i7', brand: 'Intel' },
    { processor: 'Core i7 Extreme', brand: 'Intel' },
    { processor: 'Core i9', brand: 'Intel' },
    { processor: 'Pentium', brand: 'Intel' },
    { processor: 'Pentium Gold', brand: 'Intel' },
    { processor: 'Xeon E', brand: 'Intel' },
    { processor: 'Xeon E3', brand: 'Intel' },
    { processor: 'Xeon E5', brand: 'Intel' },
]

export const cpuGenData = [
    { gen: "12th", codename: "Alder Lake", brand: 'Intel' },
    { gen: "11th", codename: "Rocket Lake", brand: 'Intel' },
    { gen: "10th", codename: "Comet Lake", brand: 'Intel' },
    { gen: "9th", codename: "Coffee Lake Refresh", brand: 'Intel' },
    { gen: "8th", codename: "Coffee Lake", brand: 'Intel' },
    { gen: "7th", codename: "Kaby Lake", brand: 'Intel' },
    { gen: "6th", codename: "Skylake", brand: 'Intel' },
    { gen: "5th", codename: "Haswell", brand: 'Intel' },
    { gen: "4th", codename: "Broadwell", brand: 'Intel' },
    { gen: "1000 Series", codename: "Summit Ridge", brand: 'AMD ' },
    { gen: "Threadripper 1000 Series", codename: "Whitehaven", brand: 'AMD ' },
    { gen: "2000 Series", codename: "Pinnacle Ridge", brand: 'AMD ' },
    { gen: "Threadripper 2000 Series", codename: "Colfax", brand: 'AMD ' },
    { gen: "3000 Series", codename: "Matisse", brand: 'AMD ' },
    { gen: "Threadripper 3000 Series", codename: "Castle Peak", brand: 'AMD ' },
    { gen: "5000 Series", codename: "Vermeer", brand: 'AMD ' },
    { gen: "Threadripper 5000 Series", codename: "Castle Peak", brand: 'AMD ' },
    { gen: "7000 Series", codename: "Raphael", brand: 'AMD ' },
]

export const socketData = [
    { socketName: "AM1" },
    { socketName: "AM2+" },
    { socketName: "AM3" },
    { socketName: "AM3+" },
    { socketName: "AM4" },
    { socketName: "AM5" },
    { socketName: "FM1" },
    { socketName: "FM2" },
    { socketName: "FM2+" },
    { socketName: "G34" },
    { socketName: "LGA 771" },
    { socketName: "LGA 775" },
    { socketName: "FCLGA1150" },
    { socketName: "LGA 1150" },
    { socketName: "LGA 1151" },
    { socketName: "LGA 1155" },
    { socketName: "LGA 1156" },
    { socketName: "LGA 1200" },
    { socketName: "LGA 1356" },
    { socketName: "LGA 1366" },
    { socketName: "LGA 1700" },
    { socketName: "LGA 2011" },
    { socketName: "LGA 2011-3" },
    { socketName: "LGA 2066" },
    { socketName: "TR4" },
    { socketName: "sTR4" },
    { socketName: "sTRX4" },
    { socketName: "sWRX8" },
]

export const cpuTypeData = [
    { gen: '12th', processor: 'Core i3', brand: 'Intel', socket: 'LGA 1700' },
    { gen: '12th', processor: 'Core i5', brand: 'Intel', socket: 'LGA 1700' },
    { gen: '12th', processor: 'Core i7', brand: 'Intel', socket: 'LGA 1700' },
    { gen: '12th', processor: 'Core i9', brand: 'Intel', socket: 'LGA 1700' },

    { gen: '11th', processor: 'Core i3', brand: 'Intel', socket: 'LGA 1200' },
    { gen: '11th', processor: 'Core i5', brand: 'Intel', socket: 'LGA 1200' },
    { gen: '11th', processor: 'Core i7', brand: 'Intel', socket: 'LGA 1200' },
    { gen: '11th', processor: 'Core i9', brand: 'Intel', socket: 'LGA 1200' },

    { gen: '10th', processor: 'Core i3', brand: 'Intel', socket: 'LGA 1200' },
    { gen: '10th', processor: 'Core i5', brand: 'Intel', socket: 'LGA 1200' },
    { gen: '10th', processor: 'Core i7', brand: 'Intel', socket: 'LGA 1200' },
    { gen: '10th', processor: 'Core i9', brand: 'Intel', socket: 'LGA 1200' },

    { gen: '9th', processor: 'Core i3', brand: 'Intel', socket: 'LGA 1151' },
    { gen: '9th', processor: 'Core i5', brand: 'Intel', socket: 'LGA 1151' },
    { gen: '9th', processor: 'Core i7', brand: 'Intel', socket: 'LGA 1151' },
    { gen: '9th', processor: 'Core i9', brand: 'Intel', socket: 'LGA 1151' },

    { gen: '8th', processor: 'Core i3', brand: 'Intel', socket: 'LGA 1151' },
    { gen: '8th', processor: 'Core i5', brand: 'Intel', socket: 'LGA 1151' },
    { gen: '8th', processor: 'Core i7', brand: 'Intel', socket: 'LGA 1151' },
    { gen: '8th', processor: 'Core i9', brand: 'Intel', socket: 'LGA 1151' },

    { gen: '7th', processor: 'Core i3', brand: 'Intel', socket: 'LGA 1151' },
    { gen: '7th', processor: 'Core i5', brand: 'Intel', socket: 'LGA 1151' },
    { gen: '7th', processor: 'Core i7', brand: 'Intel', socket: 'LGA 1151' },
    { gen: '7th', processor: 'Core i7', brand: 'Intel', socket: 'LGA 2066' },
    { gen: '7th', processor: 'Core i9', brand: 'Intel', socket: 'LGA 2066' },

    { gen: '6th', processor: 'Core i3', brand: 'Intel', socket: 'LGA 1151' },
    { gen: '6th', processor: 'Core i5', brand: 'Intel', socket: 'LGA 1151' },
    { gen: '6th', processor: 'Core i7', brand: 'Intel', socket: 'LGA 1151' },
    { gen: '6th', processor: 'Core i9', brand: 'Intel', socket: 'LGA 1151' },

    { gen: '5th', processor: 'Core i3', brand: 'Intel', socket: 'LGA 1150' },
    { gen: '5th', processor: 'Core i5', brand: 'Intel', socket: 'LGA 1150' },
    { gen: '5th', processor: 'Core i7', brand: 'Intel', socket: 'LGA 1150' },
    { gen: '5th', processor: 'Core i9', brand: 'Intel', socket: 'LGA 1150' },

    { gen: '4th', processor: 'Core i3', brand: 'Intel', socket: 'LGA 1150' },
    { gen: '4th', processor: 'Core i5', brand: 'Intel', socket: 'LGA 1150' },
    { gen: '4th', processor: 'Core i7', brand: 'Intel', socket: 'LGA 1150' },
    { gen: '4th', processor: 'Core i9', brand: 'Intel', socket: 'LGA 1150' },

    { gen: '1000 Series', processor: 'Ryzen 3', brand: 'AMD', socket: 'AM4' },
    { gen: '1000 Series', processor: 'Ryzen 5', brand: 'AMD', socket: 'AM4' },
    { gen: '1000 Series', processor: 'Ryzen 7', brand: 'AMD', socket: 'AM4' },
    { gen: '1000 Series', processor: 'Threadripper', brand: 'AMD', socket: 'TR4' },

    { gen: '2000 Series', processor: 'Ryzen 3', brand: 'AMD', socket: 'AM4' },
    { gen: '2000 Series', processor: 'Ryzen 5', brand: 'AMD', socket: 'AM4' },
    { gen: '2000 Series', processor: 'Ryzen 7', brand: 'AMD', socket: 'AM4' },
    { gen: '2000 Series', processor: 'Threadripper', brand: 'AMD', socket: 'TR4' },

    { gen: '3000 Series', processor: 'Ryzen 3', brand: 'AMD', socket: 'AM4' },
    { gen: '3000 Series', processor: 'Ryzen 5', brand: 'AMD', socket: 'AM4' },
    { gen: '3000 Series', processor: 'Ryzen 7', brand: 'AMD', socket: 'AM4' },
    { gen: '3000 Series', processor: 'Ryzen 9', brand: 'AMD', socket: 'AM4' },
    { gen: '3000 Series', processor: 'Threadripper', brand: 'AMD', socket: 'sTRX4' },

    { gen: '5000 Series', processor: 'Ryzen 3', brand: 'AMD', socket: 'AM4' },
    { gen: '5000 Series', processor: 'Ryzen 5', brand: 'AMD', socket: 'AM4' },
    { gen: '5000 Series', processor: 'Ryzen 7', brand: 'AMD', socket: 'AM4' },
    { gen: '5000 Series', processor: 'Ryzen 9', brand: 'AMD', socket: 'AM4' },
    { gen: '5000 Series', processor: 'Threadripper', brand: 'AMD', socket: 'sWRX8' },

    { gen: '7000 Series', processor: 'Ryzen 3', brand: 'AMD', socket: 'AM5' },
    { gen: '7000 Series', processor: 'Ryzen 5', brand: 'AMD', socket: 'AM5' },
    { gen: '7000 Series', processor: 'Ryzen 7', brand: 'AMD', socket: 'AM5' },
    { gen: '7000 Series', processor: 'Ryzen 9', brand: 'AMD', socket: 'AM5' },
]

export const cpuData = [
    {
        cpuId: uuidv4(),
        name: 'AMD Ryzen 5 5600X',
        coreCount: 6,
        coreClock: '3.7 GHz',
        boostClock: '4.6 GHz',
        TDP: '65 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/amd-ryzen-5-5600x.jpg',
        socket: 'AM4',
        gen: '5000 Series',
        processor: 'Ryzen 5',
        price: 158,
        brand: 'AMD'
    },
    {
        cpuId: uuidv4(),
        name: 'AMD Ryzen 7 5800X',
        coreCount: 8,
        coreClock: '3.8 GHz',
        boostClock: '4.7 GHz',
        TDP: '105 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/amd-ryzen-7-5800x.jpg',
        socket: 'AM4',
        gen: '5000 Series',
        processor: 'Ryzen 7',
        price: 243.43,
        brand: 'AMD'
    },
    {
        cpuId: uuidv4(),
        name: 'AMD Ryzen 5 5600',
        coreCount: 6,
        coreClock: '3.5 GHz',
        boostClock: '4.4 GHz',
        TDP: '65 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/amd-ryzen-5-5600.jpg',
        socket: 'AM4',
        gen: '5000 Series',
        processor: 'Ryzen 5',
        price: 118.99,
        brand: 'AMD'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i7-12700K',
        coreCount: 12,
        coreClock: '3.6 GHz',
        boostClock: '5 GHz',
        TDP: '125 W',
        iGpu: 'Intel UHD Graphics 770',
        imgUrl: '/image/products/cpu/intel-core-i7-12700k.jpg',
        socket: 'LGA 1700',
        gen: '12th',
        processor: 'Core i7',
        price: 347.69,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i5-12600K',
        coreCount: 10,
        coreClock: '3.7 GHz',
        boostClock: '4.9 GHz',
        TDP: '125 W',
        iGpu: 'Intel UHD Graphics 770',
        imgUrl: '/image/products/cpu/intel-core-i5-12600k.jpg',
        socket: 'LGA 1700',
        gen: '12th',
        processor: 'Core i5',
        price: 279.98,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i9-13900K',
        coreCount: 24,
        coreClock: '3 GHz',
        boostClock: '5.8 GHz',
        TDP: '125 W',
        iGpu: 'Intel UHD Graphics 770',
        imgUrl: '/image/products/cpu/intel-core-i9-13900k.jpg',
        socket: 'LGA 1700',
        gen: '12th',
        processor: 'Core i9',
        price: 625,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i5-12400F',
        coreCount: 6,
        coreClock: '2.5 GHz',
        boostClock: '4.4 GHz',
        TDP: '65 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/intel-core-i5-12400f.jpg',
        socket: 'LGA 1700',
        gen: '12th',
        processor: 'Core i5',
        price: 159.97,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'AMD Ryzen 9 5900X',
        coreCount: 12,
        coreClock: '3.7 GHz',
        boostClock: '4.8 GHz',
        TDP: '105 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/amd-ryzen-9-5900x.jpg',
        socket: 'AM4',
        gen: '5000 Series',
        processor: 'Ryzen 9',
        price: 343.9,
        brand: 'AMD'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i5-13600K',
        coreCount: 14,
        coreClock: '3.5 GHz',
        boostClock: '5.1 GHz',
        TDP: '125 W',
        iGpu: 'Intel UHD Graphics 770',
        imgUrl: '/image/products/cpu/intel-core-i5-13600k.jpg',
        socket: 'LGA 1700',
        gen: '12th',
        processor: 'Core i5',
        price: 300,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'AMD Ryzen 7 5800X3D',
        coreCount: 8,
        coreClock: '3.4 GHz',
        boostClock: '4.5 GHz',
        TDP: '105 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/amd-ryzen-7-5800x3d.jpg',
        socket: 'AM4',
        gen: '5000 Series',
        processor: 'Ryzen 7',
        price: 402.2,
        brand: 'AMD'
    },
    {
        cpuId: uuidv4(),
        name: 'AMD Ryzen 9 7950X',
        coreCount: 16,
        coreClock: '4.5 GHz',
        boostClock: '5.7 GHz',
        TDP: '170 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/amd-ryzen-9-7950x.jpg',
        socket: 'AM5',
        gen: '7000 Series',
        processor: 'Ryzen 9',
        price: 698.99,
        brand: 'AMD'
    },
    {
        cpuId: uuidv4(),
        name: 'AMD Ryzen 5 5600G',
        coreCount: 6,
        coreClock: '3.9 GHz',
        boostClock: '4.4 GHz',
        TDP: '65 W',
        iGpu: 'Radeon Vega 7',
        imgUrl: '/image/products/cpu/amd-ryzen-5-5600g.jpg',
        socket: 'AM4',
        gen: '5000 Series',
        processor: 'Ryzen 5',
        price: 110.51,
        brand: 'AMD'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i9-12900K',
        coreCount: 16,
        coreClock: '3.2 GHz',
        boostClock: '5.2 GHz',
        TDP: '125 W',
        iGpu: 'Intel UHD Graphics 770',
        imgUrl: '/image/products/cpu/intel-core-i9-12900k.jpg',
        socket: 'LGA 1700',
        gen: '12th',
        processor: 'Core i9',
        price: 499.89,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i7-13700K',
        coreCount: 16,
        coreClock: '3.4 GHz',
        boostClock: '5.4 GHz',
        TDP: '125 W',
        iGpu: 'Intel UHD Graphics 770',
        imgUrl: '/image/products/cpu/intel-core-i7-13700k.jpg',
        socket: 'LGA 1700',
        gen: '12th',
        processor: 'Core i7',
        price: 439.99,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'AMD Ryzen 7 7700X',
        coreCount: 8,
        coreClock: '4.5 GHz',
        boostClock: '5.4 GHz',
        TDP: '105 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/amd-ryzen-7-7700x.jpg',
        socket: 'AM5',
        gen: '7000 Series',
        processor: 'Ryzen 7',
        price: 398.98,
        brand: 'AMD'
    },
    {
        cpuId: uuidv4(),
        name: 'AMD Ryzen 5 7600X',
        coreCount: 6,
        coreClock: '4.7 GHz',
        boostClock: '5.3 GHz',
        TDP: '105 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/amd-ryzen-5-7600x.jpg',
        socket: 'AM5',
        gen: '7000 Series',
        processor: 'Ryzen 5',
        price: 299,
        brand: 'AMD'
    },
    {
        cpuId: uuidv4(),
        name: 'AMD Ryzen 7 5700X',
        coreCount: 8,
        coreClock: '3.4 GHz',
        boostClock: '4.6 GHz',
        TDP: '65 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/amd-ryzen-7-5700x.jpg',
        socket: 'AM4',
        gen: '5000 Series',
        processor: 'Ryzen 7',
        price: 227.05,
        brand: 'AMD'
    },
    {
        cpuId: uuidv4(),
        name: 'AMD Ryzen 5 3600',
        coreCount: 6,
        coreClock: '3.6 GHz',
        boostClock: '4.2 GHz',
        TDP: '65 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/amd-ryzen-5-3600.jpg',
        socket: 'AM4',
        gen: '3000 Series',
        processor: 'Ryzen 5',
        price: 0,
        brand: 'AMD'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i3-12100F',
        coreCount: 4,
        coreClock: '3.3 GHz',
        boostClock: '4.3 GHz',
        TDP: '58 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/intel-core-i3-12100f.jpg',
        socket: 'LGA 1700',
        gen: '12th',
        processor: 'Core i3',
        price: 105.98,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'AMD Ryzen 5 5500',
        coreCount: 6,
        coreClock: '3.6 GHz',
        boostClock: '4.2 GHz',
        TDP: '65 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/amd-ryzen-5-5500.jpg',
        socket: 'AM4',
        gen: '5000 Series',
        processor: 'Ryzen 5',
        price: 99,
        brand: 'AMD'
    },
    {
        cpuId: uuidv4(),
        name: 'AMD Ryzen 9 7900X',
        coreCount: 12,
        coreClock: '4.7 GHz',
        boostClock: '5.6 GHz',
        TDP: '170 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/amd-ryzen-9-7900x.jpg',
        socket: 'AM5',
        gen: '7000 Series',
        processor: 'Ryzen 9',
        price: 549,
        brand: 'AMD'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i5-13600KF',
        coreCount: 14,
        coreClock: '3.5 GHz',
        boostClock: '5.1 GHz',
        TDP: '125 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/intel-core-i5-13600kf.jpg',
        socket: 'LGA 1700',
        gen: '12th',
        processor: 'Core i5',
        price: 309.98,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'AMD Ryzen 9 5950X',
        coreCount: 16,
        coreClock: '3.4 GHz',
        boostClock: '4.9 GHz',
        TDP: '105 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/amd-ryzen-9-5950x.jpg',
        socket: 'AM4',
        gen: '5000 Series',
        processor: 'Ryzen 9',
        price: 549,
        brand: 'AMD'
    },
    {
        cpuId: uuidv4(),
        name: 'AMD Ryzen 7 5700G',
        coreCount: 8,
        coreClock: '3.8 GHz',
        boostClock: '4.6 GHz',
        TDP: '65 W',
        iGpu: 'Radeon Vega 8',
        imgUrl: '/image/products/cpu/amd-ryzen-7-5700g.jpg',
        socket: 'AM4',
        gen: '5000 Series',
        processor: 'Ryzen 7',
        price: 186.3,
        brand: 'AMD'
    },
    {
        cpuId: uuidv4(),
        name: 'AMD Ryzen 5 4500',
        coreCount: 6,
        coreClock: '3.6 GHz',
        boostClock: '4.1 GHz',
        TDP: '65 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/amd-ryzen-5-4500.jpg',
        socket: 'AM4',
        gen: '3000 Series',
        processor: 'Ryzen 5',
        price: 78.98,
        brand: 'AMD'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i5-10400F',
        coreCount: 6,
        coreClock: '2.9 GHz',
        boostClock: '4.3 GHz',
        TDP: '65 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/intel-core-i5-10400f.jpg',
        socket: 'LGA 1200',
        gen: '10th',
        processor: 'Core i5',
        price: 128.99,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i3-10100F',
        coreCount: 4,
        coreClock: '3.6 GHz',
        boostClock: '4.3 GHz',
        TDP: '65 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/intel-core-i3-10100f.jpg',
        socket: 'LGA 1200',
        gen: '10th',
        processor: 'Core i3',
        price: 81.99,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i5-12400',
        coreCount: 6,
        coreClock: '2.5 GHz',
        boostClock: '4.4 GHz',
        TDP: '65 W',
        iGpu: 'Intel UHD Graphics 730',
        imgUrl: '/image/products/cpu/intel-core-i5-12400.jpg',
        socket: 'LGA 1700',
        gen: '12th',
        processor: 'Core i5',
        price: 189.99,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'AMD Ryzen 7 3700X',
        coreCount: 8,
        coreClock: '3.6 GHz',
        boostClock: '4.4 GHz',
        TDP: '65 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/amd-ryzen-7-3700x.jpg',
        socket: 'AM4',
        gen: '3000 Series',
        processor: 'Ryzen 7',
        price: 0,
        brand: 'AMD'
    },
    {
        cpuId: uuidv4(),
        name: 'AMD Threadripper 3990X',
        coreCount: 64,
        coreClock: '2.9 GHz',
        boostClock: '4.3 GHz',
        TDP: '280 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/amd-threadripper-3990x.jpg',
        socket: 'sTRX4',
        gen: '3000 Series',
        processor: 'Threadripper',
        price: 8400,
        brand: 'AMD'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i9-13900KF',
        coreCount: 24,
        coreClock: '3 GHz',
        boostClock: '5.8 GHz',
        TDP: '125 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/intel-core-i9-13900kf.jpg',
        socket: 'LGA 1700',
        gen: '12th',
        processor: 'Core i9',
        price: 629.99,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i7-11700K',
        coreCount: 8,
        coreClock: '3.6 GHz',
        boostClock: '5 GHz',
        TDP: '125 W',
        iGpu: 'Intel UHD Graphics 750',
        imgUrl: '/image/products/cpu/intel-core-i7-11700k.jpg',
        socket: 'LGA 1200',
        gen: '11th',
        processor: 'Core i7',
        price: 290,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i5-12600KF',
        coreCount: 10,
        coreClock: '3.7 GHz',
        boostClock: '4.9 GHz',
        TDP: '125 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/intel-core-i5-12600kf.jpg',
        socket: 'LGA 1700',
        gen: '12th',
        processor: 'Core i5',
        price: 264.99,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i7-12700KF',
        coreCount: 12,
        coreClock: '3.6 GHz',
        boostClock: '5 GHz',
        TDP: '125 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/intel-core-i7-12700kf.jpg',
        socket: 'LGA 1700',
        gen: '12th',
        processor: 'Core i7',
        price: 358.97,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i7-13700KF',
        coreCount: 16,
        coreClock: '3.4 GHz',
        boostClock: '5.4 GHz',
        TDP: '125 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/intel-core-i7-13700kf.jpg',
        socket: 'LGA 1700',
        gen: '12th',
        processor: 'Core i7',
        price: 421.41,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i7-10700K',
        coreCount: 8,
        coreClock: '3.8 GHz',
        boostClock: '5.1 GHz',
        TDP: '125 W',
        iGpu: 'Intel UHD Graphics 630',
        imgUrl: '/image/products/cpu/intel-core-i7-10700k.jpg',
        socket: 'LGA 1200',
        gen: '10th',
        processor: 'Core i7',
        price: 265.99,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i7-12700F',
        coreCount: 12,
        coreClock: '2.1 GHz',
        boostClock: '4.9 GHz',
        TDP: '65 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/intel-core-i7-12700f.jpg',
        socket: 'LGA 1700',
        gen: '12th',
        processor: 'Core i7',
        price: 329.99,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i5-11400F',
        coreCount: 6,
        coreClock: '2.6 GHz',
        boostClock: '4.4 GHz',
        TDP: '65 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/intel-core-i5-11400f.jpg',
        socket: 'LGA 1200',
        gen: '11th',
        processor: 'Core i5',
        price: 161.79,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i9-12900KS',
        coreCount: 16,
        coreClock: '3.4 GHz',
        boostClock: '5.5 GHz',
        TDP: '150 W',
        iGpu: 'Intel UHD Graphics 770',
        imgUrl: '/image/products/cpu/intel-core-i9-12900ks.jpg',
        socket: 'LGA 1700',
        gen: '12th',
        processor: 'Core i9',
        price: 593.9,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'AMD Ryzen 9 3900X',
        coreCount: 12,
        coreClock: '3.8 GHz',
        boostClock: '4.6 GHz',
        TDP: '105 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/amd-ryzen-9-3900x.jpg',
        socket: 'AM4',
        gen: '3000 Series',
        processor: 'Ryzen 9',
        price: 359.99,
        brand: 'AMD'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i3-12100',
        coreCount: 4,
        coreClock: '3.3 GHz',
        boostClock: '4.3 GHz',
        TDP: '60 W',
        iGpu: 'Intel UHD Graphics 730',
        imgUrl: '/image/products/cpu/intel-core-i3-12100.jpg',
        socket: 'LGA 1700',
        gen: '12th',
        processor: 'Core i3',
        price: 137.99,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i9-11900K',
        coreCount: 8,
        coreClock: '3.5 GHz',
        boostClock: '5.3 GHz',
        TDP: '125 W',
        iGpu: 'Intel UHD Graphics 750',
        imgUrl: '/image/products/cpu/intel-core-i9-11900k.jpg',
        socket: 'LGA 1200',
        gen: '11th',
        processor: 'Core i9',
        price: 368.98,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i7-9700K',
        coreCount: 8,
        coreClock: '3.6 GHz',
        boostClock: '4.9 GHz',
        TDP: '95 W',
        iGpu: 'Intel UHD Graphics 630',
        SMT: 'No',
        imgUrl: '/image/products/cpu/intel-core-i7-9700k.jpg',
        socket: 'LGA 1151',
        gen: '9th',
        price: 430,
        processor: 'Core i7',
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i9-10900K',
        coreCount: 10,
        coreClock: '3.7 GHz',
        boostClock: '5.3 GHz',
        TDP: '125 W',
        iGpu: 'Intel UHD Graphics 630',
        imgUrl: '/image/products/cpu/intel-core-i9-10900k.jpg',
        socket: 'LGA 1200',
        gen: '10th',
        processor: 'Core i9',
        price: 346.99,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'AMD Ryzen 5 2600',
        coreCount: 6,
        coreClock: '3.4 GHz',
        boostClock: '3.9 GHz',
        TDP: '65 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/amd-ryzen-5-2600.jpg',
        socket: 'AM4',
        gen: '2000 Series',
        processor: 'Ryzen 5',
        price: 210,
        brand: 'AMD'
    },
    {
        cpuId: uuidv4(),
        name: 'AMD Ryzen 5 4600G',
        coreCount: 6,
        coreClock: '3.7 GHz',
        boostClock: '4.2 GHz',
        TDP: '65 W',
        iGpu: 'Radeon Vega 7',
        imgUrl: '/image/products/cpu/amd-ryzen-5-4600g.jpg',
        socket: 'AM4',
        gen: '3000 Series',
        processor: 'Ryzen 5',
        price: 113.55,
        brand: 'AMD'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i3-10105F',
        coreCount: 4,
        coreClock: '3.7 GHz',
        boostClock: '4.4 GHz',
        TDP: '65 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/intel-core-i3-10105f.jpg',
        socket: 'LGA 1200',
        gen: '10th',
        processor: 'Core i3',
        price: 79.97,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i9-9900K',
        coreCount: 8,
        coreClock: '3.6 GHz',
        boostClock: '5 GHz',
        TDP: '95 W',
        iGpu: 'Intel UHD Graphics 630',
        imgUrl: '/image/products/cpu/intel-core-i9-9900k.jpg',
        socket: 'LGA 1151',
        gen: '9th',
        processor: 'Core i9',
        price: 520,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i5-11600K',
        coreCount: 6,
        coreClock: '3.9 GHz',
        boostClock: '4.9 GHz',
        TDP: '125 W',
        iGpu: 'Intel UHD Graphics 750',
        imgUrl: '/image/products/cpu/intel-core-i5-11600k.jpg',
        socket: 'LGA 1200',
        gen: '11th',
        processor: 'Core i5',
        price: 255.99,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'AMD Ryzen 3 3200G',
        coreCount: 4,
        coreClock: '3.6 GHz',
        boostClock: '4 GHz',
        TDP: '65 W',
        iGpu: 'Radeon Vega 8',
        SMT: 'No',
        imgUrl: '/image/products/cpu/amd-ryzen-3-3200g.jpg',
        socket: 'AM4',
        gen: '3000 Series',
        price: 107.95,
        processor: 'Ryzen 3',
        brand: 'AMD'
    },
    {
        cpuId: uuidv4(),
        name: 'AMD Ryzen 5 3600X',
        coreCount: 6,
        coreClock: '3.8 GHz',
        boostClock: '4.4 GHz',
        TDP: '95 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/amd-ryzen-5-3600x.jpg',
        socket: 'AM4',
        gen: '3000 Series',
        processor: 'Ryzen 5',
        price: 245,
        brand: 'AMD'
    },
    {
        cpuId: uuidv4(),
        name: 'AMD Ryzen 7 2700X',
        coreCount: 8,
        coreClock: '3.7 GHz',
        boostClock: '4.3 GHz',
        TDP: '105 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/amd-ryzen-7-2700x.jpg',
        socket: 'AM4',
        gen: '2000 Series',
        processor: 'Ryzen 7',
        price: 230,
        brand: 'AMD'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i7-8700K',
        coreCount: 6,
        coreClock: '3.7 GHz',
        boostClock: '4.7 GHz',
        TDP: '95 W',
        iGpu: 'Intel UHD Graphics 630',
        imgUrl: '/image/products/cpu/intel-core-i7-8700k.jpg',
        socket: 'LGA 1151',
        gen: '8th',
        processor: 'Core i7',
        price: 322.58,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i9-12900KF',
        coreCount: 16,
        coreClock: '3.2 GHz',
        boostClock: '5.2 GHz',
        TDP: '125 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/intel-core-i9-12900kf.jpg',
        socket: 'LGA 1700',
        gen: '12th',
        processor: 'Core i9',
        price: 489,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i7-11700KF',
        coreCount: 8,
        coreClock: '3.6 GHz',
        boostClock: '5 GHz',
        TDP: '125 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/intel-core-i7-11700kf.jpg',
        socket: 'LGA 1200',
        gen: '11th',
        processor: 'Core i7',
        price: 293.99,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'AMD Ryzen 7 3800X',
        coreCount: 8,
        coreClock: '3.9 GHz',
        boostClock: '4.5 GHz',
        TDP: '105 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/amd-ryzen-7-3800x.jpg',
        socket: 'AM4',
        gen: '3000 Series',
        processor: 'Ryzen 7',
        price: 280,
        brand: 'AMD'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i5-9400F',
        coreCount: 6,
        coreClock: '2.9 GHz',
        boostClock: '4.1 GHz',
        TDP: '65 W',
        iGpu: 'None',
        SMT: 'No',
        imgUrl: '/image/products/cpu/intel-core-i5-9400f.jpg',
        socket: 'LGA 1151',
        gen: '9th',
        price: 134,
        processor: 'Core i5',
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i5-10400',
        coreCount: 6,
        coreClock: '2.9 GHz',
        boostClock: '4.3 GHz',
        TDP: '65 W',
        iGpu: 'Intel UHD Graphics 630',
        imgUrl: '/image/products/cpu/intel-core-i5-10400.jpg',
        socket: 'LGA 1200',
        gen: '10th',
        processor: 'Core i5',
        price: 151.99,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i5-12600',
        coreCount: 6,
        coreClock: '3.3 GHz',
        boostClock: '4.8 GHz',
        TDP: '65 W',
        iGpu: 'Intel UHD Graphics 770',
        imgUrl: '/image/products/cpu/intel-core-i5-12600.jpg',
        socket: 'LGA 1700',
        gen: '12th',
        processor: 'Core i5',
        price: 249.99,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i7-7700K',
        coreCount: 4,
        coreClock: '4.2 GHz',
        boostClock: '4.5 GHz',
        TDP: '91 W',
        iGpu: 'Intel HD Graphics 630',
        imgUrl: '/image/products/cpu/intel-core-i7-7700k.jpg',
        socket: 'LGA 2066',
        gen: '7th',
        processor: 'Core i7',
        price: 355,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i7-12700',
        coreCount: 12,
        coreClock: '2.1 GHz',
        boostClock: '4.9 GHz',
        TDP: '65 W',
        iGpu: 'Intel UHD Graphics 770',
        imgUrl: '/image/products/cpu/intel-core-i7-12700.jpg',
        socket: 'LGA 1700',
        gen: '12th',
        processor: 'Core i7',
        price: 379.97,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'AMD Ryzen 3 4100',
        coreCount: 4,
        coreClock: '3.8 GHz',
        boostClock: '4 GHz',
        TDP: '65 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/amd-ryzen-3-4100.jpg',
        socket: 'AM4',
        gen: '3000 Series',
        processor: 'Ryzen 3',
        price: 114,
        brand: 'AMD'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i5-11400',
        coreCount: 6,
        coreClock: '2.6 GHz',
        boostClock: '4.4 GHz',
        TDP: '65 W',
        iGpu: 'Intel UHD Graphics 730',
        imgUrl: '/image/products/cpu/intel-core-i5-11400.jpg',
        socket: 'LGA 1200',
        gen: '11th',
        processor: 'Core i5',
        price: 183.99,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i7-6700K',
        coreCount: 4,
        coreClock: '4 GHz',
        boostClock: '4.2 GHz',
        TDP: '91 W',
        iGpu: 'Intel HD Graphics 530',
        imgUrl: '/image/products/cpu/intel-core-i7-6700k.jpg',
        socket: 'LGA 1151',
        gen: '6th',
        processor: 'Core i7',
        price: 250,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i3-10100',
        coreCount: 4,
        coreClock: '3.6 GHz',
        boostClock: '4.3 GHz',
        TDP: '65 W',
        iGpu: 'Intel UHD Graphics 630',
        imgUrl: '/image/products/cpu/intel-core-i3-10100.jpg',
        socket: 'LGA 1200',
        gen: '10th',
        processor: 'Core i3',
        price: 99.99,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i5-10600K',
        coreCount: 6,
        coreClock: '4.1 GHz',
        boostClock: '4.8 GHz',
        TDP: '125 W',
        iGpu: 'Intel UHD Graphics 630',
        imgUrl: '/image/products/cpu/intel-core-i5-10600k.jpg',
        socket: 'LGA 1200',
        gen: '10th',
        processor: 'Core i5',
        price: 199.92,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i5-9600K',
        coreCount: 6,
        coreClock: '3.7 GHz',
        boostClock: '4.6 GHz',
        TDP: '95 W',
        iGpu: 'Intel UHD Graphics 630',
        SMT: 'No',
        imgUrl: '/image/products/cpu/intel-core-i5-9600k.jpg',
        socket: 'LGA 1151',
        gen: '9th',
        price: 230,
        processor: 'Core i5',
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i5-12500',
        coreCount: 6,
        coreClock: '3 GHz',
        boostClock: '4.6 GHz',
        TDP: '65 W',
        iGpu: 'Intel UHD Graphics 770',
        imgUrl: '/image/products/cpu/intel-core-i5-12500.jpg',
        socket: 'LGA 1700',
        gen: '12th',
        processor: 'Core i5',
        price: 230.99,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'AMD Ryzen 5 2600X',
        coreCount: 6,
        coreClock: '3.6 GHz',
        boostClock: '4.2 GHz',
        TDP: '95 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/amd-ryzen-5-2600x.jpg',
        socket: 'AM4',
        gen: '2000 Series',
        processor: 'Ryzen 5',
        price: 219,
        brand: 'AMD'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i7-10700F',
        coreCount: 8,
        coreClock: '2.9 GHz',
        boostClock: '4.8 GHz',
        TDP: '65 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/intel-core-i7-10700f.jpg',
        socket: 'LGA 1200',
        gen: '10th',
        processor: 'Core i7',
        price: 249.99,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'AMD Ryzen 3 3100',
        coreCount: 4,
        coreClock: '3.6 GHz',
        boostClock: '3.9 GHz',
        TDP: '65 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/amd-ryzen-3-3100.jpg',
        socket: 'AM4',
        gen: '3000 Series',
        processor: 'Ryzen 3',
        price: 149.99,
        brand: 'AMD'
    },
    {
        cpuId: uuidv4(),
        name: 'AMD Ryzen 9 3950X',
        coreCount: 16,
        coreClock: '3.5 GHz',
        boostClock: '4.7 GHz',
        TDP: '105 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/amd-ryzen-9-3950x.jpg',
        socket: 'AM4',
        gen: '3000 Series',
        processor: 'Ryzen 9',
        price: 610,
        brand: 'AMD'
    },
    {
        cpuId: uuidv4(),
        name: 'AMD Ryzen 5 3400G',
        coreCount: 4,
        coreClock: '3.7 GHz',
        boostClock: '4.2 GHz',
        TDP: '65 W',
        iGpu: 'Radeon Vega 11',
        imgUrl: '/image/products/cpu/amd-ryzen-5-3400g.jpg',
        socket: 'AM4',
        gen: '3000 Series',
        processor: 'Ryzen 5',
        price: 148.97,
        brand: 'AMD'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i7-4790K',
        coreCount: 4,
        coreClock: '4 GHz',
        boostClock: '4.4 GHz',
        TDP: '88 W',
        iGpu: 'Intel HD Graphics 4600',
        imgUrl: '/image/products/cpu/intel-core-i7-4790k.jpg',
        socket: 'LGA 1150',
        gen: '4th',
        processor: 'Core i7',
        price: 0,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i9-10850K',
        coreCount: 10,
        coreClock: '3.6 GHz',
        boostClock: '5.2 GHz',
        TDP: '125 W',
        iGpu: 'Intel UHD Graphics 630',
        imgUrl: '/image/products/cpu/intel-core-i9-10850k.jpg',
        socket: 'LGA 1200',
        gen: '10th',
        processor: 'Core i9',
        price: 349.99,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i7-8700',
        coreCount: 6,
        coreClock: '3.2 GHz',
        boostClock: '4.6 GHz',
        TDP: '65 W',
        iGpu: 'Intel UHD Graphics 630',
        imgUrl: '/image/products/cpu/intel-core-i7-8700.jpg',
        socket: 'LGA 1151',
        gen: '8th',
        processor: 'Core i7',
        price: 320,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i7-10700KF',
        coreCount: 8,
        coreClock: '3.8 GHz',
        boostClock: '5.1 GHz',
        TDP: '125 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/intel-core-i7-10700kf.jpg',
        socket: 'LGA 1200',
        gen: '10th',
        processor: 'Core i7',
        price: 289.99,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i5-11600KF',
        coreCount: 6,
        coreClock: '3.9 GHz',
        boostClock: '4.9 GHz',
        TDP: '125 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/intel-core-i5-11600kf.jpg',
        socket: 'LGA 1200',
        gen: '11th',
        processor: 'Core i5',
        price: 199.9,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'AMD Threadripper 3970X',
        coreCount: 32,
        coreClock: '3.7 GHz',
        boostClock: '4.5 GHz',
        TDP: '280 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/amd-threadripper-3970x.jpg',
        socket: 'sTRX4',
        gen: '3000 Series',
        processor: 'Threadripper',
        price: 3450,
        brand: 'AMD'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i5-10600KF',
        coreCount: 6,
        coreClock: '4.1 GHz',
        boostClock: '4.8 GHz',
        TDP: '125 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/intel-core-i5-10600kf.jpg',
        socket: 'LGA 1200',
        gen: '10th',
        processor: 'Core i5',
        price: 169.99,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i5-8400',
        coreCount: 6,
        coreClock: '2.8 GHz',
        boostClock: '4 GHz',
        TDP: '65 W',
        iGpu: 'Intel UHD Graphics 630',
        SMT: 'No',
        imgUrl: '/image/products/cpu/intel-core-i5-8400.jpg',
        socket: 'LGA 1151',
        gen: '8th',
        price: 195,
        processor: 'Core i5',
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i9-10900KF',
        coreCount: 10,
        coreClock: '3.7 GHz',
        boostClock: '5.3 GHz',
        TDP: '125 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/intel-core-i9-10900kf.jpg',
        socket: 'LGA 1200',
        gen: '10th',
        processor: 'Core i9',
        price: 339.99,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i5-6600K',
        coreCount: 4,
        coreClock: '3.5 GHz',
        boostClock: '3.9 GHz',
        TDP: '91 W',
        iGpu: 'Intel HD Graphics 530',
        SMT: 'No',
        imgUrl: '/image/products/cpu/intel-core-i5-6600k.jpg',
        socket: 'LGA 1151',
        gen: '6th',
        price: 160,
        processor: 'Core i5',
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'AMD Ryzen 5 1600',
        coreCount: 6,
        coreClock: '3.2 GHz',
        boostClock: '3.6 GHz',
        TDP: '65 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/amd-ryzen-5-1600.jpg',
        socket: 'AM4',
        gen: '1000 Series',
        processor: 'Ryzen 5',
        price: 176.1,
        brand: 'AMD'
    },
    {
        cpuId: uuidv4(),
        name: 'AMD Threadripper 3960X',
        coreCount: 24,
        coreClock: '3.8 GHz',
        boostClock: '4.5 GHz',
        TDP: '280 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/amd-threadripper-3960x.jpg',
        socket: 'sTRX4',
        gen: '3000 Series',
        processor: 'Threadripper',
        price: 2010.1,
        brand: 'AMD'
    },
    {
        cpuId: uuidv4(),
        name: 'AMD Ryzen 7 3700X',
        coreCount: 8,
        coreClock: '3.6 GHz',
        boostClock: '4.4 GHz',
        TDP: '65 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/amd-ryzen-7-3700x.jpg',
        socket: 'AM4',
        gen: '3000 Series',
        processor: 'Ryzen 7',
        price: 0,
        brand: 'AMD'
    },
    {
        cpuId: uuidv4(),
        name: 'AMD Threadripper 2990WX',
        coreCount: 32,
        coreClock: '3 GHz',
        boostClock: '4.2 GHz',
        TDP: '250 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/amd-threadripper-2990wx.jpg',
        socket: 'TR4',
        gen: '2000 Series',
        processor: 'Threadripper',
        price: 2990,
        brand: 'AMD'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i7-11700F',
        coreCount: 8,
        coreClock: '2.5 GHz',
        boostClock: '4.9 GHz',
        TDP: '65 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/intel-core-i7-11700f.jpg',
        socket: 'LGA 1200',
        gen: '11th',
        processor: 'Core i7',
        price: 275.99,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'AMD Ryzen 5 1600',
        coreCount: 6,
        coreClock: '3.2 GHz',
        boostClock: '3.6 GHz',
        TDP: '65 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/amd-ryzen-5-1600.jpg',
        socket: 'AM4',
        gen: '1000 Series',
        processor: 'Ryzen 5',
        price: 176.1,
        brand: 'AMD'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i7-10700',
        coreCount: 8,
        coreClock: '2.9 GHz',
        boostClock: '4.8 GHz',
        TDP: '65 W',
        iGpu: 'Intel UHD Graphics 630',
        imgUrl: '/image/products/cpu/intel-core-i7-10700.jpg',
        socket: 'LGA 1200',
        gen: '10th',
        processor: 'Core i7',
        price: 268.99,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i5-8600K',
        coreCount: 6,
        coreClock: '3.6 GHz',
        boostClock: '4.3 GHz',
        TDP: '95 W',
        iGpu: 'Intel UHD Graphics 630',
        SMT: 'No',
        imgUrl: '/image/products/cpu/intel-core-i5-8600k.jpg',
        socket: 'LGA 1151',
        gen: '8th',
        price: 260,
        processor: 'Core i5',
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i7-7700',
        coreCount: 4,
        coreClock: '3.6 GHz',
        boostClock: '4.2 GHz',
        TDP: '65 W',
        iGpu: 'Intel HD Graphics 630',
        imgUrl: '/image/products/cpu/intel-core-i7-7700.jpg',
        socket: 'LGA 2066',
        gen: '7th',
        processor: 'Core i7',
        price: 285,
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'AMD Ryzen 3 2200G',
        coreCount: 4,
        coreClock: '3.5 GHz',
        boostClock: '3.7 GHz',
        TDP: '65 W',
        iGpu: 'Radeon Vega 8',
        SMT: 'No',
        imgUrl: '/image/products/cpu/amd-ryzen-3-2200g.jpg',
        socket: 'AM4',
        gen: '2000 Series',
        price: 180,
        processor: 'Ryzen 3',
        brand: 'AMD'
    },
    {
        cpuId: uuidv4(),
        name: 'Intel Core i5-6500',
        coreCount: 4,
        coreClock: '3.2 GHz',
        boostClock: '3.6 GHz',
        TDP: '65 W',
        iGpu: 'Intel HD Graphics 530',
        SMT: 'No',
        imgUrl: '/image/products/cpu/intel-core-i5-6500.jpg',
        socket: 'LGA 1151',
        gen: '6th',
        price: 130,
        processor: 'Core i5',
        brand: 'Intel'
    },
    {
        cpuId: uuidv4(),
        name: 'AMD Ryzen 5 3600',
        coreCount: 6,
        coreClock: '3.6 GHz',
        boostClock: '4.2 GHz',
        TDP: '65 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/amd-ryzen-5-3600.jpg',
        socket: 'AM4',
        gen: '3000 Series',
        processor: 'Ryzen 5',
        price: 0,
        brand: 'AMD'
    },
    {
        cpuId: uuidv4(),
        name: 'AMD Ryzen 7 2700',
        coreCount: 8,
        coreClock: '3.2 GHz',
        boostClock: '4.1 GHz',
        TDP: '65 W',
        iGpu: 'None',
        imgUrl: '/image/products/cpu/amd-ryzen-7-2700.jpg',
        socket: 'AM4',
        gen: '2000 Series',
        processor: 'Ryzen 7',
        price: 260,
        brand: 'AMD'
    }
]