import { v4 as uuidv4 } from 'uuid';


export const mouseData = [
    {
        mouseId: uuidv4(),
        mouseName: 'Logitech G502 HERO',
        imgUrl: "/images/products/mouse/125c1da538a8704be799ef12a506e177.256p.jpg",
        brand: 'Logitech',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 25600,
        hand: 'Right',
        color: 'Black',
        price: 39.23,

    }, {
        mouseId: uuidv4(),
        mouseName: 'FinalMouse Air58 Ninja',
        imgUrl: "/images/products/mouse/41DpZd6MjrL.jpg",
        brand: 'FinalMouse',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 3200,
        hand: 'Right',
        color: 'Blue',
        price: 679.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Logitech G Pro X Superlight',
        imgUrl: "/images/products/mouse/31Ub3hpjHWL.jpg",
        brand: 'Logitech',
        trackingMethod: 'Optical',
        conectType: 'Wireless',
        dpi: 25400,
        hand: 'Right',
        color: 'Black',
        price: 131.45,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Logitech G502 LIGHTSPEED',
        imgUrl: "/images/products/mouse/688ab5cb5e71622cfe889c082d784cdb.256p.jpg",
        brand: 'Logitech',
        trackingMethod: 'Optical',
        conectType: 'Wireless',
        dpi: 25600,
        hand: 'Right',
        color: 'Black',
        price: 127.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Razer DeathAdder V2',
        imgUrl: "/images/products/mouse/314e9xMJUhL.jpg",
        brand: 'Razer',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 20000,
        hand: 'Right',
        color: 'Black',
        price: 42.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Razer Viper Mini',
        imgUrl: "/images/products/mouse/31MH38XvIqL.jpg",
        brand: 'Razer',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 8500,
        hand: 'Right',
        color: 'Black',
        price: 19.98,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Logitech G305 (Black)',
        imgUrl: "/images/products/mouse/0041ec7f09c5b96850347e2254991f73.256p.jpg",
        brand: 'Logitech',
        trackingMethod: 'Optical',
        conectType: 'Wireless',
        dpi: 12000,
        hand: 'Right',
        color: 'Black',
        price: 36.18,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Razer Basilisk V3',
        imgUrl: "/images/products/mouse/d662cc7b90e3fd45502f7c77d9b54269.256p.jpg",
        brand: 'Razer',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 26000,
        hand: 'Right',
        color: 'Black',
        price: 63.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Glorious Model O',
        imgUrl: "/images/products/mouse/4224f428c644018d89a196bc67631462.256p.jpg",
        brand: 'Glorious',
        trackingMethod: 'Optical',
        conectType: 'Wireless',
        dpi: 19000,
        hand: 'Right',
        color: 'White',
        price: 71.59,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Logitech G Pro X Superlight',
        imgUrl: "/images/products/mouse/31Hn3R2Vv5L.jpg",
        brand: 'Logitech',
        trackingMethod: 'Optical',
        conectType: 'Wireless',
        dpi: 25400,
        hand: 'Right',
        color: 'White',
        price: 132.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Logitech G Pro Wireless',
        imgUrl: "/images/products/mouse/800bb5629053de7c02501a11b4e0f87d.256p.jpg",
        brand: 'Logitech',
        trackingMethod: 'Optical',
        conectType: 'Wireless',
        dpi: 25600,
        hand: 'Both',
        color: 'Black',
        price: 91.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Razer Basilisk X HyperSpeed',
        imgUrl: "/images/products/mouse/41oOvmaIzYL.jpg",
        brand: 'Razer',
        trackingMethod: 'Optical',
        conectType: 'Wireless',
        dpi: 16000,
        hand: 'Right',
        color: 'Black / Green',
        price: 37.98,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Glorious Model O',
        imgUrl: "/images/products/mouse/2d8a80560eb714c71d668a6ec1bf4f96.256p.jpg",
        brand: 'Glorious',
        trackingMethod: 'Optical',
        conectType: 'Wireless',
        dpi: 19000,
        hand: 'Right',
        color: 'Black',
        price: 79.98,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Razer Viper Ultimate w/Dock',
        imgUrl: "/images/products/mouse/0164b1a008c25224ac32d76cd1223380.256p.jpg",
        brand: 'Razer',
        trackingMethod: 'Optical',
        conectType: 'Wireless',
        dpi: 20000,
        hand: 'Both',
        color: 'Black',
        price: 74.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Logitech B100',
        imgUrl: "/images/products/mouse/31iFF1KbkpL.jpg",
        brand: 'Logitech',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 800,
        hand: 'Both',
        color: 'Black',
        price: 6.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Glorious MODEL O',
        imgUrl: "/images/products/mouse/ab7f3f6e7b4d49a7dbaec72d7ec00b2b.256p.jpg",
        brand: 'Glorious',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 12000,
        hand: 'Right',
        color: 'Black',
        price: 44.75,

    }, {
        mouseId: uuidv4(),
        mouseName: 'SteelSeries Rival 3',
        imgUrl: "/images/products/mouse/24c3004e0bf166466ca2e8cf1ab55490.256p.jpg",
        brand: 'SteelSeries',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 8500,
        hand: 'Right',
        color: 'Black',
        price: 20.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Corsair DARK CORE RGB PRO SE',
        imgUrl: "/images/products/mouse/fbeb5a62840993fa50c1836186087dfc.256p.jpg",
        brand: 'Corsair',
        trackingMethod: 'Optical',
        conectType: 'Wireless',
        dpi: 18000,
        hand: 'Right',
        color: 'Black',
        price: 94.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Razer Viper V2 Pro',
        imgUrl: "/images/products/mouse/31glu1YEFwL.jpg",
        brand: 'Razer',
        trackingMethod: 'Optical',
        conectType: 'Wireless',
        dpi: 30000,
        hand: 'Right',
        color: 'Black',
        price: 121.12,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Corsair M65 RGB ELITE',
        imgUrl: "/images/products/mouse/3ece5106e64716cae7c9023a8bdf8d59.256p.jpg",
        brand: 'Corsair',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 17997,
        hand: 'Right',
        color: 'Black',
        price: 39.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Logitech G305 LIGHTSPEED',
        imgUrl: "/images/products/mouse/9c7bb4a616fae14e76530d835a82f12d.256p.jpg",
        brand: 'Logitech',
        trackingMethod: 'Optical',
        conectType: 'Wireless',
        dpi: 12000,
        hand: 'Right',
        color: 'Black',
        price: 34.95,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Logitech G700s',
        imgUrl: "/images/products/mouse/51VdAZz7I9L.jpg",
        brand: 'Logitech',
        trackingMethod: 'Laser',
        conectType: 'Wireless',
        dpi: 8200,
        hand: 'Right',
        color: 'Black',
        price: 420.00,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Logitech G305 (White)',
        imgUrl: "/images/products/mouse/e5ae54669b6dc857c4d03a26e70ed9d5.256p.jpg",
        brand: 'Logitech',
        trackingMethod: 'Optical',
        conectType: 'Wireless',
        dpi: 12000,
        hand: 'Right',
        color: 'White',
        price: 37.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Logitech G203 Lightsync',
        imgUrl: "/images/products/mouse/b8e80e45051e0b167cbda318107448f9.256p.jpg",
        brand: 'Logitech',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 8000,
        hand: 'Right',
        color: 'Black',
        price: 19.98,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Razer DeathAdder Essential',
        imgUrl: "/images/products/mouse/430bfeab57e003dfb6c1d292339e1df8.256p.jpg",
        brand: 'Razer',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 6400,
        hand: 'Right',
        color: 'Black / Green',
        price: 18.98,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Razer Viper V2 Pro',
        imgUrl: "/images/products/mouse/bc83693b4c2c338e8bcb261cf33466bb.256p.jpg",
        brand: 'Razer',
        trackingMethod: 'Optical',
        conectType: 'Wireless',
        dpi: 30000,
        hand: 'Right',
        color: 'White',
        price: 127.50,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Corsair HARPOON RGB PRO',
        imgUrl: "/images/products/mouse/4ca5b63fecc2a7fc4094c9da2c127ac8.256p.jpg",
        brand: 'Corsair',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 12000,
        hand: 'Right',
        color: 'Black',
        price: 26.72,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Glorious MODEL O',
        imgUrl: "/images/products/mouse/89c77ccaf0bdca3bde6bcc2d3890f6cb.256p.jpg",
        brand: 'Glorious',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 12000,
        hand: 'Right',
        color: 'White',
        price: 44.75,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Logitech G703 LIGHTSPEED',
        imgUrl: "/images/products/mouse/a3ff804c87be83ea9e268dd26afe13da.256p.jpg",
        brand: 'Logitech',
        trackingMethod: 'Optical',
        conectType: 'Wireless',
        dpi: 25600,
        hand: 'Right',
        color: 'Black',
        price: 76.18,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Logitech G502 Proteus Spectrum',
        imgUrl: "/images/products/mouse/196cfc73981cd14257b11cc3b0a3b8f9.256p.jpg",
        brand: 'Logitech',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 12000,
        hand: 'Right',
        color: 'Black',
        price: 84.71,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Verbatim 98113',
        imgUrl: "/images/products/mouse/e68c83700ec204d722f08c0a5c2a0b81.256p.jpg",
        brand: 'Verbatim',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 8500,
        hand: 'Both',
        color: 'Black',
        price: 4.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Corsair NIGHTSWORD RGB',
        imgUrl: "/images/products/mouse/41puSbyNS7L.jpg",
        brand: 'Corsair',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 18000,
        hand: 'Right',
        color: 'Black',
        price: 68.64,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Razer Basilisk Ultimate',
        imgUrl: "/images/products/mouse/61eb5935b25d0e35424629b707f22c03.256p.jpg",
        brand: 'Razer',
        trackingMethod: 'Optical',
        conectType: 'Wireless',
        dpi: 20000,
        hand: 'Right',
        color: 'Black',
        price: 99.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Razer Naga Trinity',
        imgUrl: "/images/products/mouse/6b73ce755ef3fdebd30ac433ab829664.256p.jpg",
        brand: 'Razer',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 16000,
        hand: 'Right',
        color: 'Black',
        price: 79.98,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Corsair M65 RGB ULTRA WIRELESS',
        imgUrl: "/images/products/mouse/8c2320c4b1f286232ed2e0765180589c.256p.jpg",
        brand: 'Corsair',
        trackingMethod: 'Optical',
        conectType: 'Wireless',
        dpi: 26000,
        hand: 'Right',
        color: 'Black / Silver',
        price: 121.75,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Logitech MX Master 3',
        imgUrl: "/images/products/mouse/d3a9b615f187bce607d610088fbbfdfd.256p.jpg",
        brand: 'Logitech',
        trackingMethod: 'Laser',
        conectType: 'Wireless',
        dpi: 4000,
        hand: 'Right',
        color: 'Black / Silver',
        price: 85.00,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Corsair M65 RGB ELITE',
        imgUrl: "/images/products/mouse/5b398a22dedb28c16624f46920fd0c4f.256p.jpg",
        brand: 'Corsair',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 17995,
        hand: 'Right',
        color: 'White',
        price: 59.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Razer DeathAdder V2 Pro',
        imgUrl: "/images/products/mouse/e081ddfb8c66371eb0d090672f19af59.256p.jpg",
        brand: 'Razer',
        trackingMethod: 'Optical',
        conectType: 'Wireless',
        dpi: 20000,
        hand: 'Right',
        color: 'Black',
        price: 65.00,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Razer Basilisk V3 Pro + Mouse Dock Pro',
        imgUrl: "/images/products/mouse/f3ac232d47683dd615b3d89f99e1bba2.256p.jpg",
        brand: 'Razer',
        trackingMethod: 'Optical',
        conectType: 'Wired, Wireless, Bluetooth Wireless',
        dpi: 30000,
        hand: 'Right',
        color: 'Black',
        price: 199.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Redragon M602',
        imgUrl: "/images/products/mouse/31+XikWYoSL.jpg",
        brand: 'Redragon',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 7200,
        hand: 'Right',
        color: 'Black',
        price: 16.98,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Razer DeathAdder V3 Pro',
        imgUrl: "/images/products/mouse/21RzGl38CsL.jpg",
        brand: 'Razer',
        trackingMethod: 'Optical',
        conectType: 'Wireless',
        dpi: 30000,
        hand: 'Right',
        color: 'Black',
        price: 142.49,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Logitech G303 Daedalus Apex',
        imgUrl: "/images/products/mouse/41EaCtcC7oL.jpg",
        brand: 'Logitech',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 12000,
        hand: 'Right',
        color: 'Black / Orange',
        price: 289.95,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Razer Viper Ultimate',
        imgUrl: "/images/products/mouse/31PR+RfutWL.jpg",
        brand: 'Razer',
        trackingMethod: 'Optical',
        conectType: 'Wireless',
        dpi: 20000,
        hand: 'Both',
        color: 'Black',
        price: 66.49,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Logitech G402',
        imgUrl: "/images/products/mouse/41sMQGodbiL.jpg",
        brand: 'Logitech',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 4000,
        hand: 'Right',
        color: 'Black',
        price: 34.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Corsair HARPOON RGB',
        imgUrl: "/images/products/mouse/3769ffe225dff8702ca903ffce27846f.256p.jpg",
        brand: 'Corsair',
        trackingMethod: 'Optical',
        conectType: 'Wireless',
        dpi: 10000,
        hand: 'Right',
        color: 'Black',
        price: 37.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'SteelSeries Aerox 3',
        imgUrl: "/images/products/mouse/aa5f7764bd01a4136c66c6980fccd89e.256p.jpg",
        brand: 'SteelSeries',
        trackingMethod: 'Optical',
        conectType: 'Bluetooth Wireless',
        dpi: 18000,
        hand: 'Right',
        color: 'Black',
        price: 99.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Logitech G502 SE HERO',
        imgUrl: "/images/products/mouse/1352f08a307d6d717b48bdaf666e6fb4.256p.jpg",
        brand: 'Logitech',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 25600,
        hand: 'Right',
        color: 'Black / Silver',
        price: 39.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Razer Naga Pro',
        imgUrl: "/images/products/mouse/0615b1c07cbb01bb91060e0517d95dcd.256p.jpg",
        brand: 'Razer',
        trackingMethod: 'Optical',
        conectType: 'Wireless',
        dpi: 20000,
        hand: 'Right',
        color: 'Black',
        price: 99.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Razer Viper 8KHz',
        imgUrl: "/images/products/mouse/57e54358c52493a49f369c4374aaf201.256p.jpg",
        brand: 'Razer',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 20000,
        hand: 'Both',
        color: 'Black',
        price: 49.87,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Corsair SCIMITAR RGB ELITE',
        imgUrl: "/images/products/mouse/dfb52b07215736a9d55388366a53d86a.256p.jpg",
        brand: 'Corsair',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 18000,
        hand: 'Right',
        color: 'Black',
        price: 64.98,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Glorious MODEL D',
        imgUrl: "/images/products/mouse/67068c12e8020ae7c28be8e9202ad900.256p.jpg",
        brand: 'Glorious',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 12000,
        hand: 'Right',
        color: 'Black',
        price: 44.75,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Logitech G203 Lightsync',
        imgUrl: "/images/products/mouse/dbe9bbba752e18178e12f24bbe6ed196.256p.jpg",
        brand: 'Logitech',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 8000,
        hand: 'Right',
        color: 'White',
        price: 26.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Logitech G600 MMO Gaming Mouse',
        imgUrl: "/images/products/mouse/d86fec800f132dbefa676d13d0d9a7a4.256p.jpg",
        brand: 'Logitech',
        trackingMethod: 'Laser',
        conectType: 'Wired',
        dpi: 8200,
        hand: 'Right',
        color: 'Black',
        price: 38.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Logitech MX MASTER 3S',
        imgUrl: "/images/products/mouse/80f5ae114fd88013fa45e170e1098214.256p.jpg",
        brand: 'Logitech',
        trackingMethod: 'Optical',
        conectType: 'Wireless',
        dpi: 8000,
        hand: 'Right',
        color: 'Gray',
        price: 99.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Verbatim Bravo',
        imgUrl: "/images/products/mouse/5c388ef9bdfd2933f0cef41aa21ad5a1.256p.jpg",
        brand: 'Verbatim',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 8500,
        hand: 'Both',
        color: 'Black',
        price: 5.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Asus P707 ROG SPATHA X',
        imgUrl: "/images/products/mouse/3b425661832992431efa165c454bd178.256p.jpg",
        brand: 'Asus',
        trackingMethod: 'Optical',
        conectType: 'Wireless',
        dpi: 19000,
        hand: 'Right',
        color: 'Black',
        price: 149.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Razer Basilisk V2',
        imgUrl: "/images/products/mouse/1841b82340846f04a4fac12d496ca7a7.256p.jpg",
        brand: 'Razer',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 20000,
        hand: 'Right',
        color: 'Black',
        price: 34.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Razer Viper Ultimate w/Dock',
        imgUrl: "/images/products/mouse/ae9b1b9c8d6363d03e17b77e51343e45.256p.jpg",
        brand: 'Razer',
        trackingMethod: 'Optical',
        conectType: 'Wireless',
        dpi: 20000,
        hand: 'Both',
        color: 'Pink',
        price: 79.98,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Razer Naga Chroma',
        imgUrl: "/images/products/mouse/41DlAggBnWL.jpg",
        brand: 'Razer',
        trackingMethod: 'Laser',
        conectType: 'Wired',
        dpi: 16000,
        hand: 'Right',
        color: 'Black',
        price: 308.69,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Logitech G403 HERO',
        imgUrl: "/images/products/mouse/1e8c3800a012015b0400211b5d370aa0.256p.jpg",
        brand: 'Logitech',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 25600,
        hand: 'Right',
        color: 'Black / Blue',
        price: 44.62,

    }, {
        mouseId: uuidv4(),
        mouseName: 'HP HyperX Pulsefire Haste',
        imgUrl: "/images/products/mouse/41ZiHvROOGL.jpg",
        brand: 'HP',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 16000,
        hand: 'Right',
        color: 'Black',
        price: 29.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Logitech G903 HERO',
        imgUrl: "/images/products/mouse/bcef1163cebeee9d3001d5bafcf7d3d7.256p.jpg",
        brand: 'Logitech',
        trackingMethod: 'Optical',
        conectType: 'Wireless',
        dpi: 25600,
        hand: 'Both',
        color: 'Black',
        price: 107.50,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Redragon COBRA M711',
        imgUrl: "/images/products/mouse/41hA8MkIIHL.jpg",
        brand: 'Redragon',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 10000,
        hand: 'Right',
        color: 'Black / Multicolor',
        price: 19.98,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Logitech G604 LIGHTSPEED',
        imgUrl: "/images/products/mouse/e32b9e2d5144b118afe0cb32c5b83fed.256p.jpg",
        brand: 'Logitech',
        trackingMethod: 'Optical',
        conectType: 'Wireless',
        dpi: 25600,
        hand: 'Right',
        color: 'Black',
        price: 49.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Razer Lancehead Tournament Edition Mercury',
        imgUrl: "/images/products/mouse/41gHyYVxVwL.jpg",
        brand: 'Razer',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 16000,
        hand: 'Both',
        color: 'White / Gray',
        price: 239.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Corsair IRONCLAW RGB WIRELESS',
        imgUrl: "/images/products/mouse/31hR2kTeYoL.jpg",
        brand: 'Corsair',
        trackingMethod: 'Optical',
        conectType: 'Wireless',
        dpi: 18000,
        hand: 'Right',
        color: 'Black',
        price: 69.98,

    }, {
        mouseId: uuidv4(),
        mouseName: 'SteelSeries Rival 5',
        imgUrl: "/images/products/mouse/6d35eedc32891db22347dce86786474e.256p.jpg",
        brand: 'SteelSeries',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 18000,
        hand: 'Right',
        color: 'Black',
        price: 38.85,

    }, {
        mouseId: uuidv4(),
        mouseName: 'HP Pulsefire Core RGB',
        imgUrl: "/images/products/mouse/7ec3d99e13b9e17b324d53e507b9b5d9.256p.jpg",
        brand: 'HP',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 6200,
        hand: 'Right',
        color: 'Black',
        price: 13.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Razer Mamba Elite',
        imgUrl: "/images/products/mouse/c2346112fa183f5096da60261edf05c2.256p.jpg",
        brand: 'Razer',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 16000,
        hand: 'Right',
        color: 'Black',
        price: 39.95,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Corsair DARK CORE RGB PRO',
        imgUrl: "/images/products/mouse/41M52yTK5+L.jpg",
        brand: 'Corsair',
        trackingMethod: 'Optical',
        conectType: 'Wireless',
        dpi: 18000,
        hand: 'Right',
        color: 'Black',
        price: 69.98,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Corsair M65 PRO RGB FPS',
        imgUrl: "/images/products/mouse/210af8afefd556ec530cecb5f7eb5cbd.256p.jpg",
        brand: 'Corsair',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 12000,
        hand: 'Right',
        color: 'Black',
        price: 29.10,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Corsair SABRE RGB PRO WIRELESS CHAMPION SERIES',
        imgUrl: "/images/products/mouse/63c4b5efa625cd67a2e4771c8cfd0f38.256p.jpg",
        brand: 'Corsair',
        trackingMethod: 'Optical',
        conectType: 'Wireless',
        dpi: 26000,
        hand: 'Right',
        color: 'Black',
        price: 39.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Asus P704 ROG CHAKRAM',
        imgUrl: "/images/products/mouse/001f947a6bca968b8791442b6884fb70.256p.jpg",
        brand: 'Asus',
        trackingMethod: 'Optical',
        conectType: 'Wireless',
        dpi: 16000,
        hand: 'Right',
        color: 'Black',
        price: 132.40,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Razer Orochi V2',
        imgUrl: "/images/products/mouse/5b65da659333a26f6624d15733414fff.256p.jpg",
        brand: 'Razer',
        trackingMethod: 'Optical',
        conectType: 'Wireless',
        dpi: 18000,
        hand: 'Right',
        color: 'White',
        price: 39.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Logitech MX Master',
        imgUrl: "/images/products/mouse/31wDFiIu6iL.jpg",
        brand: 'Logitech',
        trackingMethod: 'Laser',
        conectType: 'Bluetooth Wireless',
        dpi: 1600,
        hand: 'Right',
        color: 'Brown / Black',
        price: 0,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Trust GXT 155',
        imgUrl: "/images/products/mouse/8406b72cd9f0cb137d336161e32d97a3.256p.jpg",
        brand: 'Trust',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 4000,
        hand: 'Right',
        color: 'Black / Blue',
        price: 0,

    }, {
        mouseId: uuidv4(),
        mouseName: 'SteelSeries Rival 600',
        imgUrl: "/images/products/mouse/41-F2flhq6L.jpg",
        brand: 'SteelSeries',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 12000,
        hand: 'Right',
        color: 'Black',
        price: 59.89,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Corsair SABRE RGB PRO CHAMPION SERIES',
        imgUrl: "/images/products/mouse/4702f2380d91265aab43664f32e7cb8f.256p.jpg",
        brand: 'Corsair',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 18000,
        hand: 'Right',
        color: 'Black',
        price: 57.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Razer Viper Ultimate',
        imgUrl: "/images/products/mouse/83448f14ea7aad477596baf8ae892723.256p.jpg",
        brand: 'Razer',
        trackingMethod: 'Optical',
        conectType: 'Wireless',
        dpi: 20000,
        hand: 'Both',
        color: 'White',
        price: 218.02,

    }, {
        mouseId: uuidv4(),
        mouseName: 'SteelSeries Aerox 9',
        imgUrl: "/images/products/mouse/b19f57b195a5e41b53e03b3717f4cd08.256p.jpg",
        brand: 'SteelSeries',
        trackingMethod: 'Optical',
        conectType: 'Wireless',
        dpi: 18000,
        hand: 'Right',
        color: 'Black',
        price: 109.47,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Razer Basilisk V3 Pro',
        imgUrl: "/images/products/mouse/b5ae883a17a1d332780a63f64f8df4b0.256p.jpg",
        brand: 'Razer',
        trackingMethod: 'Optical',
        conectType: 'Wired, Wireless, Bluetooth Wireless',
        dpi: 30000,
        hand: 'Right',
        color: 'Black',
        price: 159.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'SteelSeries Rival 650 Wireless',
        imgUrl: "/images/products/mouse/e44e0fffdc546ccc18ec9db334d7c71f.256p.jpg",
        brand: 'SteelSeries',
        trackingMethod: 'Optical',
        conectType: 'Wireless',
        dpi: 12000,
        hand: 'Right',
        color: 'Black',
        price: 79.95,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Razer DeathAdder V3 Pro',
        imgUrl: "/images/products/mouse/21YrdnICAjL.jpg",
        brand: 'Razer',
        trackingMethod: 'Optical',
        conectType: 'Wireless',
        dpi: 30000,
        hand: 'Right',
        color: 'White',
        price: 149.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Asus ROG Gladius III',
        imgUrl: "/images/products/mouse/d3386a7f3320b71c375d53436c318077.256p.jpg",
        brand: 'Asus',
        trackingMethod: 'Optical',
        conectType: 'Wireless',
        dpi: 26000,
        hand: 'Right',
        color: 'Black',
        price: 97.33,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Logitech MX MASTER 3S',
        imgUrl: "/images/products/mouse/80f5ae114fd88013fa45e170e1098214.256p.jpg",
        brand: 'Logitech',
        trackingMethod: 'Optical',
        conectType: 'Wireless',
        dpi: 8000,
        hand: 'Right',
        color: 'Black',
        price: 94.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Razer DeathAdder Elite',
        imgUrl: "/images/products/mouse/21ly+bIj1gS.jpg",
        brand: 'Razer',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 16000,
        hand: 'Right',
        color: 'Black / Green',
        price: 46.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Verbatim 98616 Go Mini Travel Commuter',
        imgUrl: "/images/products/mouse/c748e9772c96c374259e4badb8a2a34a.256p.jpg",
        brand: 'Verbatim',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 8500,
        hand: 'Both',
        color: 'Blue',
        price: 8.94,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Logitech G300S',
        imgUrl: "/images/products/mouse/200275a153ebdfa42c1bcdd248e3f6d8.256p.jpg",
        brand: 'Logitech',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 2500,
        hand: 'Both',
        color: 'Black / Blue',
        price: 24.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Logitech MX MASTER 3S',
        imgUrl: "/images/products/mouse/487d6f4109b89a3e2c44fa934dd43b2c.256p.jpg",
        brand: 'Logitech',
        trackingMethod: 'Optical',
        conectType: 'Wireless',
        dpi: 8000,
        hand: 'Right',
        color: 'White',
        price: 94.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Logitech M90',
        imgUrl: "/images/products/mouse/3942bf430d7f5b33bd01e2b0d0b7abdb.256p.jpg",
        brand: 'Logitech',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 1000,
        hand: 'Both',
        color: 'Black',
        price: 8.91,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Glorious MODEL D',
        imgUrl: "/images/products/mouse/e53580d579186aabe0bad312bfeae3ee.256p.jpg",
        brand: 'Glorious',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 12000,
        hand: 'Right',
        color: 'White',
        price: 44.75,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Glorious Model O-',
        imgUrl: "/images/products/mouse/c0dfd77aad137727f2bfa6e03304a001.256p.jpg",
        brand: 'Glorious',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 12000,
        hand: 'Right',
        color: 'Black',
        price: 44.75,

    }, {
        mouseId: uuidv4(),
        mouseName: 'SteelSeries Rival 3',
        imgUrl: "/images/products/mouse/178a8d67052dc8ac01b07c8b84924a0b.256p.jpg",
        brand: 'SteelSeries',
        trackingMethod: 'Optical',
        conectType: 'Wireless',
        dpi: 18000,
        hand: 'Right',
        color: 'Black',
        price: 42.39,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Logitech G502 X Plus',
        imgUrl: "/images/products/mouse/313vjNMPw3L.jpg",
        brand: 'Logitech',
        trackingMethod: 'Optical',
        conectType: 'Wired, Wired, Wireless',
        dpi: 25600,
        hand: 'Right',
        color: 'Black',
        price: 151.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Logitech M100',
        imgUrl: "/images/products/mouse/0dd8486ae196d3bd49621b0647075be6.256p.jpg",
        brand: 'Logitech',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 1000,
        hand: 'Both',
        color: 'Black',
        price: 8.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'NZXT Lift',
        imgUrl: "/images/products/mouse/f413ef023ef6470d1fc4e581ee15314a.256p.jpg",
        brand: 'NZXT',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 16000,
        hand: 'Right',
        color: 'Black',
        price: 41.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'HP HyperX Pulsefire FPS Pro',
        imgUrl: "/images/products/mouse/5427199f410131967602f3fc7a0b2c7a.256p.jpg",
        brand: 'HP',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 16000,
        hand: 'Right',
        color: 'Black',
        price: 24.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Logitech G903',
        imgUrl: "/images/products/mouse/41hj-bvIpbL.jpg",
        brand: 'Logitech',
        trackingMethod: 'Optical',
        conectType: 'Wireless',
        dpi: 12000,
        hand: 'Both',
        color: 'Black / Blue',
        price: 99.99,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Logitech MX MASTER 2S (Black)',
        imgUrl: "/images/products/mouse/41qc6XU1MWL.jpg",
        brand: 'Logitech',
        trackingMethod: 'Laser',
        conectType: 'Wireless',
        dpi: 4000,
        hand: 'Right',
        color: 'Black',
        price: 72.40,

    }, {
        mouseId: uuidv4(),
        mouseName: 'Cooler Master MM711 Matte White',
        imgUrl: "/images/products/mouse/29e700d66dec0bef323bcb2ea6ddf7b9.256p.jpg",
        brand: 'Cooler Master',
        trackingMethod: 'Optical',
        conectType: 'Wired',
        dpi: 16000,
        hand: 'Right',
        color: 'White',
        price: 19.00,

    }]