export const producerData = [
    { brand: 'AMD ', directLink: '', imgUrl: '' },
    { brand: 'Intel', directLink: '', imgUrl: '' },
    { brand: 'Samsung', directLink: '', imgUrl: '' },
    { brand: 'Nvidia', directLink: '', imgUrl: '' },
    { brand: 'Acer', directLink: '', imgUrl: '' },
    { brand: 'Asus', directLink: '', imgUrl: '' },
    { brand: 'HP', directLink: '', imgUrl: '' },
    { brand: 'Lenovo', directLink: '', imgUrl: '' },
    { brand: 'MSI', directLink: '', imgUrl: '' },
    { brand: 'Gigabyte', directLink: '', imgUrl: '' },
    { brand: 'ASRock', directLink: '', imgUrl: '' },
    { brand: 'NZXT', directLink: '', imgUrl: '' },
    { brand: 'Corsair', directLink: '', imgUrl: '' },
    { brand: 'G.Skill', directLink: '', imgUrl: '' },
    { brand: 'Silicon', directLink: '', imgUrl: '' },
    { brand: 'Kingston', directLink: '', imgUrl: '' },
    { brand: 'TEAMGROUP', directLink: '', imgUrl: '' },
    { brand: 'Crucial', directLink: '', imgUrl: '' },
    { brand: 'Patriot', directLink: '', imgUrl: '' },
    { brand: 'PNY', directLink: '', imgUrl: '' },
    { brand: 'EVGA', directLink: '', imgUrl: '' },
    { brand: 'XFX', directLink: '', imgUrl: '' },
    { brand: 'Zotac', directLink: '', imgUrl: '' },
    { brand: 'Sapphire', directLink: '', imgUrl: '' },
    { brand: 'PowerColor', directLink: '', imgUrl: '' },
    { brand: 'Seagate', directLink: '', imgUrl: '' },
    { brand: 'Western Digital', directLink: '', imgUrl: '' },
    { brand: 'WD', directLink: '', imgUrl: '' },
    { brand: 'Sabrent', directLink: '', imgUrl: '' },
    { brand: 'SK Hynix', directLink: '', imgUrl: '' },
    { brand: 'Leven', directLink: '', imgUrl: '' },
    { brand: 'Timetec', directLink: '', imgUrl: '' },
    { brand: 'Logitech', directLink: '', imgUrl: '' },
    { brand: 'FinalMouse', directLink: '', imgUrl: '' },
    { brand: 'Razer', directLink: '', imgUrl: '' },
    { brand: 'Glorious', directLink: '', imgUrl: '' },
    { brand: 'SteelSeries', directLink: '', imgUrl: '' },
    { brand: 'Verbatim', directLink: '', imgUrl: '' },
    { brand: 'Redragon', directLink: '', imgUrl: '' },
    { brand: 'Trust', directLink: '', imgUrl: '' },
    { brand: 'Cooler Master', directLink: '', imgUrl: '' },
    { brand: 'Alienware', directLink: '', imgUrl: '' },
    { brand: 'LG', directLink: '', imgUrl: '' },
    { brand: 'Dell', directLink: '', imgUrl: '' },
    { brand: 'AOC', directLink: '', imgUrl: '' },
    { brand: 'ViewSonic', directLink: '', imgUrl: '' },
    { brand: 'Sceptre', directLink: '', imgUrl: '' },
    { brand: 'BenQ', directLink: '', imgUrl: '' },
    { brand: 'VIOTEK', directLink: '', imgUrl: '' },
]