export { default as CpuOverview } from './CpuOverview.vue'
export { default as MainboardOverview } from './MainboardOverview.vue'
export { default as MonitorOverview } from './MonitorOverview.vue'
export { default as MouseOverview } from './MouseOverview.vue'
export { default as RamOverview } from './RamOverview.vue'
export { default as StorageDriveOverview } from './StorageDriveOverview.vue'
export { default as VideoCardOverview } from './VideoCardOverview.vue'